/**
 * Error codes matching contracts/errors.md
 * All error messages are in Chinese as per specification
 */

export const ErrorCodes = {
  // Authentication Errors (AUTH_)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_DEVICE_LIMIT_EXCEEDED: 'AUTH_DEVICE_LIMIT_EXCEEDED',
  AUTH_DEVICE_NOT_VERIFIED: 'AUTH_DEVICE_NOT_VERIFIED',
  AUTH_MONTHLY_DEVICE_LIMIT: 'AUTH_MONTHLY_DEVICE_LIMIT',
  AUTH_SMS_CODE_INVALID: 'AUTH_SMS_CODE_INVALID',
  AUTH_SMS_CODE_EXPIRED: 'AUTH_SMS_CODE_EXPIRED',
  AUTH_OAUTH_FAILED: 'AUTH_OAUTH_FAILED',
  AUTH_GUEST_NOT_FOUND: 'AUTH_GUEST_NOT_FOUND',

  // Validation Errors (VAL_)
  VAL_INVALID_EMAIL: 'VAL_INVALID_EMAIL',
  VAL_INVALID_PHONE: 'VAL_INVALID_PHONE',
  VAL_PASSWORD_TOO_WEAK: 'VAL_PASSWORD_TOO_WEAK',
  VAL_USERNAME_TOO_SHORT: 'VAL_USERNAME_TOO_SHORT',
  VAL_USERNAME_TOO_LONG: 'VAL_USERNAME_TOO_LONG',
  VAL_REQUIRED_FIELD: 'VAL_REQUIRED_FIELD',
  VAL_INVALID_UUID: 'VAL_INVALID_UUID',
  VAL_INVALID_MODULE_TYPE: 'VAL_INVALID_MODULE_TYPE',
  VAL_INVALID_TEST_MODE: 'VAL_INVALID_TEST_MODE',
  VAL_INVALID_RATING: 'VAL_INVALID_RATING',

  // User Errors (USER_)
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  USER_PHONE_EXISTS: 'USER_PHONE_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_TRIAL_EXPIRED: 'USER_TRIAL_EXPIRED',
  USER_MEMBERSHIP_REQUIRED: 'USER_MEMBERSHIP_REQUIRED',

  // Book Errors (BOOK_)
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  BOOK_UNIT_NOT_FOUND: 'BOOK_UNIT_NOT_FOUND',
  BOOK_UNIT_LOCKED: 'BOOK_UNIT_LOCKED',
  BOOK_ACCESS_DENIED: 'BOOK_ACCESS_DENIED',

  // Learning Errors (LEARN_)
  LEARN_SESSION_NOT_FOUND: 'LEARN_SESSION_NOT_FOUND',
  LEARN_SESSION_EXPIRED: 'LEARN_SESSION_EXPIRED',
  LEARN_WORD_NOT_IN_SESSION: 'LEARN_WORD_NOT_IN_SESSION',
  LEARN_ALREADY_SUBMITTED: 'LEARN_ALREADY_SUBMITTED',
  LEARN_REINFORCEMENT_REQUIRED: 'LEARN_REINFORCEMENT_REQUIRED',

  // Review Errors (REVIEW_)
  REVIEW_BLOCKING: 'REVIEW_BLOCKING',
  REVIEW_CARD_NOT_FOUND: 'REVIEW_CARD_NOT_FOUND',
  REVIEW_CARD_NOT_DUE: 'REVIEW_CARD_NOT_DUE',
  REVIEW_ALREADY_GRADUATED: 'REVIEW_ALREADY_GRADUATED',

  // Test Errors (TEST_)
  TEST_SESSION_NOT_FOUND: 'TEST_SESSION_NOT_FOUND',
  TEST_SESSION_EXPIRED: 'TEST_SESSION_EXPIRED',
  TEST_ALREADY_SUBMITTED: 'TEST_ALREADY_SUBMITTED',
  TEST_INCOMPLETE_ANSWERS: 'TEST_INCOMPLETE_ANSWERS',
  TEST_REVIEW_REQUIRED: 'TEST_REVIEW_REQUIRED',

  // Reward Errors (REWARD_)
  REWARD_MILESTONE_NOT_REACHED: 'REWARD_MILESTONE_NOT_REACHED',
  REWARD_ALREADY_CLAIMED: 'REWARD_ALREADY_CLAIMED',
  REWARD_DAILY_CAP_REACHED: 'REWARD_DAILY_CAP_REACHED',
  REWARD_INSUFFICIENT_COINS: 'REWARD_INSUFFICIENT_COINS',

  // Rate Limit Errors (RATE_)
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  RATE_SMS_LIMIT: 'RATE_SMS_LIMIT',
  RATE_LOGIN_LIMIT: 'RATE_LOGIN_LIMIT',

  // System Errors (SYS_)
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
  SYS_EXTERNAL_SERVICE_ERROR: 'SYS_EXTERNAL_SERVICE_ERROR',
  SYS_MAINTENANCE: 'SYS_MAINTENANCE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

// Chinese error messages
export const ErrorMessages: Record<ErrorCode, string> = {
  [ErrorCodes.AUTH_INVALID_CREDENTIALS]: '用户名或密码错误',
  [ErrorCodes.AUTH_TOKEN_EXPIRED]: '登录已过期，请重新登录',
  [ErrorCodes.AUTH_TOKEN_INVALID]: '无效的登录凭证',
  [ErrorCodes.AUTH_REFRESH_TOKEN_INVALID]: '刷新令牌无效或已过期',
  [ErrorCodes.AUTH_DEVICE_LIMIT_EXCEEDED]: '设备数量超过限制（最多3台）',
  [ErrorCodes.AUTH_DEVICE_NOT_VERIFIED]: '新设备需要验证',
  [ErrorCodes.AUTH_MONTHLY_DEVICE_LIMIT]: '本月新设备添加次数已达上限',
  [ErrorCodes.AUTH_SMS_CODE_INVALID]: '验证码错误或已过期',
  [ErrorCodes.AUTH_SMS_CODE_EXPIRED]: '验证码已过期，请重新获取',
  [ErrorCodes.AUTH_OAUTH_FAILED]: '第三方登录失败',
  [ErrorCodes.AUTH_GUEST_NOT_FOUND]: '未找到游客数据',

  [ErrorCodes.VAL_INVALID_EMAIL]: '邮箱格式不正确',
  [ErrorCodes.VAL_INVALID_PHONE]: '手机号格式不正确',
  [ErrorCodes.VAL_PASSWORD_TOO_WEAK]: '密码强度不足（至少8位）',
  [ErrorCodes.VAL_USERNAME_TOO_SHORT]: '用户名至少2个字符',
  [ErrorCodes.VAL_USERNAME_TOO_LONG]: '用户名最多50个字符',
  [ErrorCodes.VAL_REQUIRED_FIELD]: '缺少必填字段',
  [ErrorCodes.VAL_INVALID_UUID]: '无效的ID格式',
  [ErrorCodes.VAL_INVALID_MODULE_TYPE]: '无效的学习模块类型',
  [ErrorCodes.VAL_INVALID_TEST_MODE]: '无效的测试模式',
  [ErrorCodes.VAL_INVALID_RATING]: '无效的评分（0-4）',

  [ErrorCodes.USER_EMAIL_EXISTS]: '该邮箱已被注册',
  [ErrorCodes.USER_PHONE_EXISTS]: '该手机号已被注册',
  [ErrorCodes.USER_NOT_FOUND]: '用户不存在',
  [ErrorCodes.USER_TRIAL_EXPIRED]: '试用期已结束，请升级会员',
  [ErrorCodes.USER_MEMBERSHIP_REQUIRED]: '此功能需要会员权限',

  [ErrorCodes.BOOK_NOT_FOUND]: '词书不存在',
  [ErrorCodes.BOOK_UNIT_NOT_FOUND]: '单元不存在',
  [ErrorCodes.BOOK_UNIT_LOCKED]: '该单元需要会员权限解锁',
  [ErrorCodes.BOOK_ACCESS_DENIED]: '无权访问此词书',

  [ErrorCodes.LEARN_SESSION_NOT_FOUND]: '学习会话不存在或已结束',
  [ErrorCodes.LEARN_SESSION_EXPIRED]: '学习会话已过期',
  [ErrorCodes.LEARN_WORD_NOT_IN_SESSION]: '该单词不在当前学习会话中',
  [ErrorCodes.LEARN_ALREADY_SUBMITTED]: '该单词已提交过答案',
  [ErrorCodes.LEARN_REINFORCEMENT_REQUIRED]: '请先完成词义强化',

  [ErrorCodes.REVIEW_BLOCKING]: '待复习单词过多，请先完成复习',
  [ErrorCodes.REVIEW_CARD_NOT_FOUND]: '学习卡片不存在',
  [ErrorCodes.REVIEW_CARD_NOT_DUE]: '该卡片尚未到复习时间',
  [ErrorCodes.REVIEW_ALREADY_GRADUATED]: '该单词已毕业，无需复习',

  [ErrorCodes.TEST_SESSION_NOT_FOUND]: '测试会话不存在',
  [ErrorCodes.TEST_SESSION_EXPIRED]: '测试已超时',
  [ErrorCodes.TEST_ALREADY_SUBMITTED]: '测试已提交',
  [ErrorCodes.TEST_INCOMPLETE_ANSWERS]: '答案不完整',
  [ErrorCodes.TEST_REVIEW_REQUIRED]: '请先完成待复习单词的学习',

  [ErrorCodes.REWARD_MILESTONE_NOT_REACHED]: '未达到领取条件',
  [ErrorCodes.REWARD_ALREADY_CLAIMED]: '奖励已领取',
  [ErrorCodes.REWARD_DAILY_CAP_REACHED]: '今日学习金币已达上限',
  [ErrorCodes.REWARD_INSUFFICIENT_COINS]: '金币余额不足',

  [ErrorCodes.RATE_LIMIT_EXCEEDED]: '请求过于频繁，请稍后再试',
  [ErrorCodes.RATE_SMS_LIMIT]: '短信发送过于频繁',
  [ErrorCodes.RATE_LOGIN_LIMIT]: '登录尝试次数过多',

  [ErrorCodes.SYS_INTERNAL_ERROR]: '系统错误，请稍后再试',
  [ErrorCodes.SYS_DATABASE_ERROR]: '数据库错误',
  [ErrorCodes.SYS_EXTERNAL_SERVICE_ERROR]: '外部服务暂时不可用',
  [ErrorCodes.SYS_MAINTENANCE]: '系统维护中',
};
