/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip
    if (request.mode !== 'navigate') {
      return false;
    }

    // If this is a URL that starts with /_, skip
    if (url.pathname.startsWith('/_')) {
      return false;
    }

    // If this looks like a URL for a resource, skip
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache API responses
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60, // 1 hour
      }),
    ],
  })
);

// Cache static assets (images, fonts, etc.)
registerRoute(
  ({ request }) =>
    request.destination === 'image' ||
    request.destination === 'font' ||
    request.destination === 'style',
  new CacheFirst({
    cacheName: 'static-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Cache audio files for offline playback
registerRoute(
  ({ request, url }) =>
    request.destination === 'audio' ||
    url.pathname.includes('/audio/') ||
    url.hostname === 'dict.youdao.com',
  new CacheFirst({
    cacheName: 'audio-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// Cache book data (vocabulary, sentences)
registerRoute(
  ({ url }) =>
    url.pathname.startsWith('/api/books/') ||
    url.pathname.startsWith('/api/words/'),
  new StaleWhileRevalidate({
    cacheName: 'book-data',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 1 day
      }),
    ],
  })
);

// Cache user-specific data with shorter expiration
registerRoute(
  ({ url }) =>
    url.pathname.startsWith('/api/cards/') ||
    url.pathname.startsWith('/api/reviews/') ||
    url.pathname.startsWith('/api/learning/'),
  new NetworkFirst({
    cacheName: 'user-data',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
);

// Listen for skip waiting message
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Background sync for offline actions
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-learning-sessions') {
    event.waitUntil(syncLearningSessions());
  } else if (event.tag === 'sync-review-submissions') {
    event.waitUntil(syncReviewSubmissions());
  }
});

/**
 * Sync pending learning sessions when back online
 */
async function syncLearningSessions() {
  try {
    const db = await openOfflineDB();
    const tx = db.transaction('learning-sessions', 'readonly');
    const store = tx.objectStore('learning-sessions');
    const sessions = await store.getAll();

    for (const session of sessions) {
      try {
        const response = await fetch('/api/learning/sessions', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(session.data),
        });

        if (response.ok) {
          // Remove from offline queue
          const deleteTx = db.transaction('learning-sessions', 'readwrite');
          const deleteStore = deleteTx.objectStore('learning-sessions');
          await deleteStore.delete(session.id);
        }
      } catch (error) {
        console.error('Failed to sync learning session:', error);
      }
    }
  } catch (error) {
    console.error('Background sync failed:', error);
  }
}

/**
 * Sync pending review submissions when back online
 */
async function syncReviewSubmissions() {
  try {
    const db = await openOfflineDB();
    const tx = db.transaction('review-submissions', 'readonly');
    const store = tx.objectStore('review-submissions');
    const submissions = await store.getAll();

    for (const submission of submissions) {
      try {
        const response = await fetch('/api/reviews/submit', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(submission.data),
        });

        if (response.ok) {
          // Remove from offline queue
          const deleteTx = db.transaction('review-submissions', 'readwrite');
          const deleteStore = deleteTx.objectStore('review-submissions');
          await deleteStore.delete(submission.id);
        }
      } catch (error) {
        console.error('Failed to sync review submission:', error);
      }
    }
  } catch (error) {
    console.error('Background sync failed:', error);
  }
}

/**
 * Open IndexedDB for offline queue
 */
function openOfflineDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('offline-queue', 1);

    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);

    request.onupgradeneeded = (event: any) => {
      const db = event.target.result;

      if (!db.objectStoreNames.contains('learning-sessions')) {
        db.createObjectStore('learning-sessions', {
          keyPath: 'id',
          autoIncrement: true,
        });
      }

      if (!db.objectStoreNames.contains('review-submissions')) {
        db.createObjectStore('review-submissions', {
          keyPath: 'id',
          autoIncrement: true,
        });
      }
    };
  });
}

// Handle fetch errors gracefully
self.addEventListener('fetch', (event: FetchEvent) => {
  event.respondWith(
    fetch(event.request).catch(() => {
      // Return cached response or offline page
      return caches.match(event.request).then((response) => {
        if (response) {
          return response;
        }
        // Return offline page for navigation requests
        if (event.request.mode === 'navigate') {
          return caches.match('/offline.html') || new Response('Offline');
        }
        return new Response('Network error', { status: 408 });
      });
    })
  );
});
